# Generated by Django 5.2.7 on 2025-10-30 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('owner', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('os', models.CharField(max_length=50)),
                ('environment', models.CharField(choices=[('DEV', 'Development'), ('TEST', 'Testing'), ('PROD', 'Production')], max_length=50)),
                ('applications', models.ManyToManyField(related_name='servers', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('applications', models.ManyToManyField(related_name='databases', to='core.application')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.server')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('applications', models.ManyToManyField(related_name='services', to='core.application')),
                ('depends_on', models.ManyToManyField(blank=True, to='core.service')),
            ],
        ),
    ]
